### ISSUE TITLE
CANs 'rx' method does not return trailing zeros in 'data'

### ISSUE THREAD

**Issue by I3I-I** [sidneycadot/pydwf#26]
If trailing zeros are received via CAN, they are not returned in data, but the message is trimmed. If you would expect something like '\x01 \x02 \x00 \x03 \x04' you only get '\x01 \x02'. 

This should be fixed by changing line 152 in 'digital_can.py' from
```data     = c_data.value[:dlc]```
to
```data     = c_data.raw[:dlc]```

Nevertheless, **thank you** for the great work. I really appreciate it!

**Comment by sidneycadot** [comment]
Hi,

Thanks for bringing this to my attention. These same mistake was present in the UART code.

I corrected the issue as per your suggestion in both places, and pushed a pydwf version 1.1.12 out the door with this improvement.

Cheers, Sidney

**Comment by I3I-I** [comment]
Great, thanks for fixing that so fast!
