### ISSUE TITLE
enumfilters no longer work

### ISSUE THREAD

**Issue by lparkes** [sidneycadot/pydwf#27]
Hi,
The ENUMFILTER for device enumeration is now a sort-of kind-of bit mask and it can't be correctly represented with a Python enum anymore. It will need to be replaced with a plain int.

As an example, if I want to only select USB connected devices that I need to specify an enumfilter of `enumfilterType|enumfilterUSB`.  If I want to only connect to the local AXI based device because I'm using Linux Mode then I need an enumfilter of `enumfilterType|enumfilterAXI`. If I want to avoid the ethernet connection, then I wll need `enumfilterType|enumfilterUSB|enumfilterAXI`. 

This isn't really feasible with Python enums.

**Comment by sidneycadot** [comment]
Thanks for the report. The enumfilter flags are indeed a bit of a mess, having changed semantics from a typical "enum" to a bitfield, but also keeping the old values around that should supposedly, making this currently a bit of a Frankenstein type.

I'll mull a bit on the best way to solve this. Bit busy currently so this could take a week or so.

**Comment by lparkes** [comment]
If I have some spare time in the next week I'll see if I can come up with a PR. Even if it don't accept the PR, it still won't cost you anything.

**Comment by sidneycadot** [comment]
Hi @lparkes -- I'm updating pydwf right now and also looking into this issue.

What I'm seeing is that even with the current release, the DwfEnumFilter  class is alsready an enum.Flag, which means it should be able to treat it as a bitfield, eg the or (pipe) operator works on those values.

In the latest version of libdwf (by Digilent), apparently support for the non-bitfield values has been removed (in v 3.20.1), so I will take them out of pydwf, too.

Given that, is there still a problem? Or can you provide an example where this doesn't work for you?

Cheers, Sidney

**Comment by lparkes** [comment]
I found the source of the problem while going over my test case code with a fine tooth comb making sure that the C and Python examples printed out exactly the same things and enough things to be sure that I know what is happening.

The value of DwfEnumFilter.Type is 0x80000000 when it should be 0x08000000. i.e. six trailing zeroes, not seven. The fact that the C source only lists seven hex digits for these filter values instead of the usual eight digits doesn't help. The Remote, Audio and Demo definitions seem to have the same problem.

Cheers,
Lloyd

**Comment by sidneycadot** [comment]
Hi Lloyd,

Great catch! It was indeed force-of habit thinking that the hex constants were 8 digits.

I made a 1.1.13 release to fix this. It is now based on DWF 3.20.1, but it doesn't doesn't support the handful of new functions yet, that will still take a few weeks.

I think we can now close this issue, right?

**Comment by lparkes** [comment]
Yes. This can be closed. Thanks.
