### ISSUE TITLE
ADP5250 Support???

### ISSUE THREAD

**Issue by Marmaduke1st** [sidneycadot/pydwf#28]
Just wondering if ADP5250 support was in the pipeline?

Or if its current has limited support?

**Comment by sidneycadot** [comment]
There is no reason it shouldn't work on WIndows, but I don't have such a device at my disposal for testing.

On Linux or macOS, no. Not supported by Digilent.

**Comment by Marmaduke1st** [comment]
Super, now i just need to convince my boss to buy me one

**Comment by sidneycadot** [comment]
Hi @Marmaduke1st .

Before you buy, consider that the ADP5250 is a rebranded National Instruments product for which some frankensteinian effort was made to make DWF work with it, under Windows only. It's a hack, really.

You may be better off with a 3250 or 3450, for many applications they have better specs. Check the datasheets.

**Comment by Marmaduke1st** [comment]
Thanks for the tip! but it the all in one element I'm after. Worth it over
say the Discovery 2 or 3 (can't seem to get a 3 in the uk)

**Comment by Marmaduke1st** [comment]
Yes sorry,

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
